minetest.register_node("farming:gardenwindy", {
	description = "Windy Garden",
	drawtype = "plantlike",
	tiles = {"garden_windy.png"},
	inventory_image = {"garden_windy.png"},
	wield_image = {"garden_windy.png"},
	waving = 1,
	paramtype = "light",
	paramtype2 = "meshoptions",
	place_param2 = 4,
	groups = {snappy = 3, flammable = 3, attached_node = 1},
	selection_box = {
		type = "fixed",
		fixed = {-6 / 16, -0.5, -6 / 16, 6 / 16, 4 / 16, 6 / 16},
	},
	drop = {items = {{items = {'farming:seed_tomato'}, rarity = 1},
		   {items = {'farming:seed_tomato'}, rarity = 2},
		   {items = {'farming:seed_tomato'}, rarity = 3},
		   {items = {'farming:seeds_cucumber'}, rarity = 1},
		   {items = {'farming:seeds_cucumber'}, rarity = 2},
		   {items = {'farming:seeds_cucumber'}, rarity = 3},
		   {items = {'farming:seed_cotton'}, rarity = 1},
		   {items = {'farming:seed_cotton'}, rarity = 2},
		   {items = {'farming:seed_cotton'}, rarity = 3},
		   {items = {'farming:garlic_clove'}, rarity = 1},
		   {items = {'farming:garlic_clove'}, rarity = 2},
		   {items = {'farming:garlic_clove'}, rarity = 3},
		   {items = {'farming:seed_corn'}, rarity = 1},
		   {items = {'farming:seed_corn'}, rarity = 2},
		   {items = {'farming:seed_corn'}, rarity = 3},
		   {items = {'farming:seed_mustard'}, rarity = 1},
		   {items = {'farming:seed_mustard'}, rarity = 2},
		   {items = {'farming:seed_mustard'}, rarity = 3},
		   {items = {'farming:seed_cabbage'}, rarity = 1},
		   {items = {'farming:seed_cabbage'}, rarity = 2},
		   {items = {'farming:seed_cabbage'}, rarity = 3},
		   {items = {'farming:leek_seeds'}, rarity = 1},
		   {items = {'farming:leek_seeds'}, rarity = 2},
		   {items = {'farming:leek_seeds'}, rarity = 3}}},
})

minetest.register_decoration({
		name = "farming:gardenwindy",
		deco_type = "simple",
		place_on = {"default:dirt_with_grass"},
		sidelen = 16,
		noise_params = {
			offset = 0,
			scale = 0.035,
			spread = {x = 100, y = 100, z = 100},
			seed = 329,
			octaves = 3,
			persist = 0.6
		},
		y_max = 30,
		y_min = 1,
		decoration = "farming:gardenwindy",
		param2 = 4,
	})